language: cpp
dist: xenial

addons:
    apt:
        sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
        - os: osx
          osx_image: xcode10
          sudo: required
          compiler: clang

install:
    - if [[ $CXX = "g++" ]]; then export CXX="g++-8"; fi
    - if [[ $TRAVIS_OS_NAME = "linux" && $CXX = "clang++" ]]; then export CXX="clang++-7"; fi

script:
    - cmake . -Bbuild
    - cmake --build build --target check
