language: cpp

addons:
    apt:
        packages:
            - clang-7
            - g++-8

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
        - os: osx
          sudo: required
          compiler: clang
    install:
        - if [[ $CXX = "g++" ]]; then export CXX="g++-8"; fi
        - if [[ $CXX = "clang++" ]]; then export CXX="clang++-7"; fi
    script:
        - cmake -S. -Bbuild
        - cmake --build build --target check
