language: cpp
dist: xenial

addons:
    apt:
        sources:
            - llvm-toolchain-xenial-7
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

stages:
    - test
    - deploy

matrix:
    include:
        - os: linux
          stage: test
          sudo: required
          compiler: gcc
          install:
              - export CXX="g++-8"
        - os: osx
          stage: test
          osx_image: xcode10
          sudo: required
          compiler: clang
        - os: windows
          stage: test
          filter_secrets: false
        - os: linux
          stage: deploy
          sudo: required
          language: python
          python: "3.6"
          compiler: gcc
          if: branch = master
          install:
              - pip install conan
          script :
              - conan create . -s compiler=gcc -s compiler.version=8.1 -e CXX=g++-8 pure-cpp/stable
          after_success:
              - conan remote add bintray https://api.bintray.com/conan/pure-cpp/pure-cpp
              - conan user -p ${BINTRAY_API_KEY} -r bintray pure-cpp
              - conan upload --all -r bintray pure-cpp/0.0.1@pure-cpp/stable


script:
    - cmake . -Bbuild
    - cmake --build build --target check
