language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-xenial-y
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - clang-7

matrix:
    include:
        - os: linux
          sudo: required
          compiler: gcc
        - os: osx
          sudo: required
          compiler: clang

install:
    - if [[ $CXX = "g++" ]]; then export CXX="g++-8"; fi
    - if [[ $CXX = "clang++" ]]; then export CXX="clang++-7"; fi

script:
    - cmake -S. -Bbuild
    - cmake --build build --target check
